### ISSUE TITLE
Unable to use `react-inspector` inside a Reflex app

### ISSUE THREAD

**Issue by cowboyd** [Industrial/reflex#1]
Hi there,

I'm trying to convert a react app that uses `react-inspector` to Deno, and I thought I would give `Reflex` a try. However, I'm getting an error whenever I try to load the page.

```
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (https://esm.sh/v83/react@17.0.2/deno/react.js:2:4838)
    at n.useMemo (https://esm.sh/v83/react@17.0.2/deno/react.js:2:6821)
    at ThemeAcceptor (https://esm.sh/v83/react-inspector@5.1.1/deno/react-inspector.js:4:5707)
    at renderWithHooks (https://esm.sh/v85/react-dom@18.1.0/deno/server.development.js:9282:24)
    at renderIndeterminateComponent (https://esm.sh/v85/react-dom@18.1.0/deno/server.development.js:9342:23)
    at renderElement (https://esm.sh/v85/react-dom@18.1.0/deno/server.development.js:9506:15)
    at renderNodeDestructive (https://esm.sh/v85/react-dom@18.1.0/deno/server.development.js:9598:17)
    at finishClassComponent (https://esm.sh/v85/react-dom@18.1.0/deno/server.development.js:9307:11)
    at renderClassComponent (https://esm.sh/v85/react-dom@18.1.0/deno/server.development.js:9315:11)
    at renderElement (https://esm.sh/v85/react-dom@18.1.0/deno/server.development.js:9503:15)
```

Here is a repository based on create-reflex-app that reproduces the issue https://github.com/cowboyd/reflex-react-inspector Any idea what's happening here?

**Comment by Industrial** [comment]
Hi.

Because we are using https://esm.sh to fetch NodeJS modules, their dependencies are bundled. This often means that multiple versions of react will be loaded.

The react import was defined as `https://esm.sh/react@18.1.0?dev` so to make sure that the same version loads with your library (and it uses the already cached version) you can add dependencies of packages in the `importMap.json` like so:

```
  "react-inspector": "https://esm.sh/react-inspector@5.1.1?deps=react@18.1.0,react-dom@18.1.0&dev"
```

For now you'll have to add dev as well for a development build as I haven't thought of a way to deploy Reflex apps to production yet (Deno Deploy, AWS Lambda, Vercel). I guess for production builds we should strip off the dev :)

**Comment by cowboyd** [comment]
Is there something that can be done to make the Error message more clear? As a new user, I was basically completely lost.
